### ISSUE TITLE
Mediawiki search: support for wildcards and complex operators

### ISSUE THREAD

**Issue by etdsoft** [securityroots/dradispro-tracker#103]
Originally reported by Sven:

> If I'm searching for a part of a string directly in the Media Wiki and
> add a wildcard like "*" I will get the results that contain this string.
> If I'm searching in the Media Wiki Import Plugin in dradis with the same
> string and a wildcard I will not get a result. I always have to enter a
> full string for a match. My questions are:
> Do I have to use other wildcards to be able to search for parts of a
> string and are Wildcards even implemented in the search function of
> MediaWiki?
> Is it possible to execute complex search queries in the Media Wiki
> Import Plugin, e.g. with Boolean Operators (&&, ||...) or a RegEx to
> filter the results?

We need to investigate if the API endpoint supports wildcards/operators and what are we missing from our side.

**Comment by rachkor** [comment]
Closing, added to internal idea backlog to investigate adding in the future.
