### ISSUE TITLE
old session cookies cause error

### ISSUE THREAD

**Issue by digininja** [securityroots/dradispro-tracker#109]
Don't know if you can do anything about this but here goes...

I had a tab open to Dradis but then Dradis VM crashed (not your fault) and so I restarted it. The browser tab then would only show the default Dradis error message till I cleared the session cookies.

I assume it is because the session didn't exist on the Dradis side and so it didn't know what to do with it, it would be good if that could be caught and rather than an error just redirect to the login page.

**Comment by rachkor** [comment]
Closing as there's not much we can do about the session/cookies. Note that you can navigate directly to /pro/logout and in many cases, that will resolve the error.
