### ISSUE TITLE
Image title

### ISSUE THREAD

**Issue by alm8i** [securityroots/dradispro-tracker#124]
We are missing Textile feature to add a title to an image in the Advanced word export plugin. In Textile if you want to add a title to an image the syntax is following:

!path_to_image(image_title)!

But the "(image_title)" part is added to image path and therefore the image can't be found.

>There was an error processing the report: No such file or directory - >/path_to_dradis/attachments/426/test.png(image_title)

**Comment by etdsoft** [comment]
This is implemented and will ship soon.
