### ISSUE TITLE
Push to VulnDB (Private) Button

### ISSUE THREAD

**Issue by n0x00** [securityroots/dradispro-tracker#126]
When Adding a Issue to your project it would be great to see a 'Publish to VulnDB' button that submits the issue to the private repo for those with the subscription 

This would be handy to populate your private issues 'as you go' and make the experience of adding them a little easier to do.

Thanks Dan!

**Comment by etdsoft** [comment]
v1.12 is shipping with push to Issuelib.

@digininja can you share the MediaWiki snippet too please?

**Comment by digininja** [comment]
Check my site for the importer I wrote a while ago, all the code is in
there.

**Comment by etdsoft** [comment]
Done, this ships in 1.12.rc2
