### ISSUE TITLE
Non-latin characters in Note Template names

### ISSUE THREAD

**Issue by etdsoft** [securityroots/dradispro-tracker#127]
Those using non-latin characters in their language should be able to include them in Note Template names as well:

![picture device independent bitmap 1](https://f.cloud.github.com/assets/53006/2523505/4c9d243a-b4d2-11e3-9891-8b57e92aebc5.jpg)

**Comment by rachkor** [comment]
Closing, added to the idea backlog to investigate adding in the future.
