### ISSUE TITLE
black on black on tab navigation

### ISSUE THREAD

**Issue by digininja** [securityroots/dradispro-tracker#130]
I've confirmed this in both Chrome and Firefox so don't think it is just my setup...

Go into a project and use tab to shift focus around the inputs. When focus is on any of the top menu items (upload, export etc) the font goes black leaving black on black so hiding the text.

Don't know if there is anything you can do about this.

**Comment by etdsoft** [comment]
Fixed ships in the next release. It only took 3 years to get those 9 letters added!
