### ISSUE TITLE
word export properties coming from another project

### ISSUE THREAD

**Issue by raesene** [securityroots/dradispro-tracker#137]
Interesting one here, not sure if it's an authorization flaw or it would only work with admin users..

We had a project that when exported to word appeared to be getting the word properties from another customers test.

Looking at it what had happened was that we'd set the note category incorrectly, so Dradis wasn't finding the properties.

I've not had a chance to look at the code as yet, but I'm guessing this is a finder based on note category and it takes the first entry it finds?  So if it fails to find one for the current project it gets one from another?

Not a big problem, but thought I should mention it while it's top of mind

**Comment by etdsoft** [comment]
Ping me if needs re-opening
