### ISSUE TITLE
Better picture naming from Ctrl+C

### ISSUE THREAD

**Issue by etdsoft** [securityroots/dradispro-tracker#144]
> A better picture naming would also be great; we're suggesting that you eliminate the .png/.jpg/.etc picture extensions, which is added by the code automatically and let the user focus on the picture name (rather than extension). It would also be great if the name of the last saved image name would be remembered and the number after it would be automatically increased by 1: instead of always presenting a default name, which needs to be deleted and renamed every single time. We suggest you save the name of the picture in a cookie, which would make it browser based and each user/browser can have it's own remembered name. For example: if the first added picture is test1.png, when uploading the next picture with Ctrl+C (copying directly from a clipboard buffer), the presented picture name should be test2.png; this requires some work, but not much, but if you don't have time to actually implement this, you should at least remember the last picture name and present the test1.png to the user (rather than screenshot-XX.png).

**Comment by rachkor** [comment]
Closing this for now, copy to clipboard was implemented.
