### ISSUE TITLE
Can't move node back to 'root' (make it a branch)

### ISSUE THREAD

**Issue by etdsoft** [securityroots/dradispro-tracker#145]
From Dimitry:

```
B. Another issue/bug or "by design" I discovered that if I accidentally move a top-level 
Node to another Node there is no way for me to move the the node that is now enclosed
back to the top level. It would be nice to have a way to do so.
```

**Comment by etdsoft** [comment]
Fixed, will ship in next release / RC.

**Comment by digininja** [comment]
Funny, I've had the same problem but hadn't got round to reporting it yet

**Comment by etdsoft** [comment]
Unbelievable! That a but got reported and fixed before you could lay a claim on it is unheard of. 

Are you loosing your edge @digininja or are we getting better at this?

**Comment by digininja** [comment]
I thought I'd reported it a while ago so wanted to check before I did it as
a new one.
