### ISSUE TITLE
Uneditable Note Causes Error

### ISSUE THREAD

**Issue by w-young** [securityroots/dradispro-tracker#154]
When using fields in a note, if you save the note with unclosed brackets such as "#[Title", you will be sent to a generic error page.  Whenever you click on this note in the project, you are unable to edit it and you will get the generic error page every time.  Must use command line to manually delete the note.

**Comment by etdsoft** [comment]
Apparently this was fixed some time ago, but we forgot to close the issue in the tracker.

Please feel free to re-open if you can reproduce in a recent version of the app.
