### ISSUE TITLE
Individual issue count

### ISSUE THREAD

**Issue by ethicalhack3r** [securityroots/dradispro-tracker#161]
It would be good to have a count of all individual issues some where. Currently there is a unique issue count, but an individual issue count would also be very useful.

For example; 1 issue is assigned to 2 nodes - the issue count would be 2.

**Comment by etdsoft** [comment]
@daltoniran 3 years too late... yes, here is the repo! https://github.com/dradis/dradis-ce

**Comment by rachkor** [comment]
Closing, these use cases should be resolved with `IssueCounter` and/or `EvidenceCounter` controls.
