### ISSUE TITLE
Issues are not connect to node (All Issues and evidence view) 

### ISSUE THREAD

**Issue by thec00n** [securityroots/dradispro-tracker#168]
We struggle with a problem that occurs when connecting an issue to an evidence. For example we have lots of issue that have the same title. The Issues would differ from each other slightly especially on the solution. When you then connect the evidence to the issue you can not see which one is the right issue, because you can only see the title.

You already provided me with a fix once, but now I downloaded the new update and the issue is there again:

./app/views/issues/_issue.html.erb
5: <%= issue.title %> [<%= issue.affected.map(&:label).join(',') %>]

./app/views/evidence/_evidence_editor.html.erb
7: <%= f.association :issue, collection: @issues, label_method: lambda {|issue| "#{issue.title} [#{issue.affected.map(&:label).join(',') }]" }, prompt: 'Choose an Issue' %>

**Comment by rachkor** [comment]
Closing. Local patches will need to be re-applied after each upgrade. New Issue/Evidence layout in Dradis v2 may resolve this.
