### ISSUE TITLE
Issue list case sensitive sorting

### ISSUE THREAD

**Issue by digininja** [securityroots/dradispro-tracker#172]
This might be deliberate but the project list sorts entries in a case sensitive way so a title of "aaa" would come at the bottom if all the rest of the entries started with a capital.

I think the sorting should not be case sensitive.

Spotted this when I created an issue about mDNS which I keep having to remember to scroll to the bottom to see.

**Comment by rachkor** [comment]
Closing, added to our internal idea backlog to investigate adding in the future.
