### ISSUE TITLE
AdvancedWordExport properties limit

### ISSUE THREAD

**Issue by minion820** [securityroots/dradispro-tracker#175]
Version 1.11.0rc14 limits the amount of Notes that can be considered AdvancedWordExport properties to one.  I have three notes that are properties used for better organization, but only one is processed into the report.  

If you combine all the notes into one the report is populated with the notes.

**Comment by etdsoft** [comment]
For the time being we're implementing a Pre-export check validator in v1.12. It will contain one check that will warn you about this if you've got more than one note in the properties category.

**Comment by rachkor** [comment]
Closing. Document Properties are now handled on the Report Content page, removing the need for Notes set to `AdvancedWordExport properties`.
