### ISSUE TITLE
Manually reorder issues to group vulnerabilities

### ISSUE THREAD

**Issue by Miketmclaughlin** [securityroots/dradispro-tracker#178]
Feature request:

Adding the ability to reorder issues within the web interface so vulnerabilities can be ordered in the report output. Not sure how feasible this is...

**Comment by etdsoft** [comment]
This is tricky as in order for the report order to be deterministic you have to assign a unique value to each issue. Some people do it by CVSS others just use a counter to control which one goes first. I'm going to close this for now as it doesn't seem likely we'll be implementing it any time soon!
