### ISSUE TITLE
Add multiple nodes to one issue

### ISSUE THREAD

**Issue by inadorel** [securityroots/dradispro-tracker#179]
For big infrastructure tests it would be really useful to be able to add nodes to an issue in bulk.  So say for example I have 100 hosts and 30 of them have SSLv2 - it would be great to be able to paste the list of addresses affected into the issue itself and have that populate to each individual node.  I did see issue #54 but not sure this was exactly what was covered.

Less critical but also useful would be to be able to add an issue straight from the node itself.  So say I am looking at a host and I notice it has SSLv2 - I would add the issue from within the node and the act of populating it there would also add it to the issues list.  I find that at the moment having to jump out to a different section, add the issue and then go back to the node breaks my train of thought....

Could we also have a plugin that adds nodes straight from a text file of IP addresses (and sorts them in the correct address order).

Many thanks Daniel (and I didn't even mention IE....) :)

**Comment by etdsoft** [comment]
The ability to add nodes to an issue in bulk (also by pasting into a textarea) was implemented in v2.4
