### ISSUE TITLE
Support spaces in field names

### ISSUE THREAD

**Issue by etdsoft** [securityroots/dradispro-tracker#18]
Originally reported by Ozan in [this post](https://groups.google.com/forum/#!topic/dradis-pro/T84nfAUkPOw) of the mailing list:

```
when i use space or turkish character in any subject i can't get report. if i don't use space or turkish charecter it's working.
```

The problem is that field names get translated to XML tags, so having something like

```
#[My Field]#
```

Results in:

```
<My Field>
```

With `Field` being interpreted as an attribute and note part of the tag.

**Comment by rachkor** [comment]
Closing. Spaces in field names will export but cannot be used for filtering. For example, use `CVSSv3.BaseScore|(9.0..10.0)` instead of `CVSSv3 Base Score|(9.0..10.0)` in Issue filters.
