### ISSUE TITLE
SSL Checklist for Pentesters - Methodology

### ISSUE THREAD

**Issue by ethicalhack3r** [securityroots/dradispro-tracker#187]
Would be nice to have this as a methodology in Dradis - http://www.exploresecurity.com/wp-content/uploads/custom/SSL_manual_cheatsheet.html

I'd do it myself buy I can't seem to figure out a 'nice' way to include _all_ of the data in that cheat sheet into a Dradis methodology.

Maybe others have some ideas?

**Comment by rachkor** [comment]
Closing. New Methodology feature should allow more details to be included: https://dradisframework.com/pro/support/guides/administration/methodology_templates.html#create
