### ISSUE TITLE
Preview image attachments on mouseover on Evidence page

### ISSUE THREAD

**Issue by marcwickenden** [securityroots/dradispro-tracker#188]
It would be handy to have a preview popover when you mouseover an image attachment in the Evidence screen. Or even a button next to the trashcan would be fine but either way, some way to view which screenshot that was without having to name the file itself. I tend to drag screenshots straight in from Snagit so you get generic names like this.

![attachments](https://cloud.githubusercontent.com/assets/1202418/4704813/326be104-5875-11e4-83f0-413091cb5ec5.png)

**Comment by rachkor** [comment]
Closing, added to our internal idea backlog to investigate adding in the future!
