### ISSUE TITLE
Drag images in evidence

### ISSUE THREAD

**Issue by stephenreda** [securityroots/dradispro-tracker#191]
It would be a cool enhancement if upload images could be dragged from the Attachments section to the body of the evidence section, directly with the right syntax. In my opinion, doing these things out of the box really enhances user exp. (f.e. the fact that #Output# is already in the evidence box (since a few upgrades now). Not a great deal to type it every time, but way more simpler not having to remember the syntax of these parameters.

**Comment by rachkor** [comment]
Closing, the screenshots were refactored and should be easier to work with in v2.#.
