### ISSUE TITLE
catching unfiltered issues

### ISSUE THREAD

**Issue by digininja** [securityroots/dradispro-tracker#195]
I've got a report that uses issue filters to pull out high, medium and low risk issues into appropriate sections. On one issue I accidentally put hihg not high, that issue then doesn't appear in the report as it doesn't match any of the filters.

Is there a way to say "dump all other issues here" so that I can manually go through them and assign them correctly?

One option I thought of was to do a negative filter, i.e. "not (high or medium or low)" but from reading the guide there are ANDs and ORs but no NOTs.

Is there a way to do this?

**Comment by rachkor** [comment]
Closing, resolved with the Validator.
