### ISSUE TITLE
bullet point bug

### ISSUE THREAD

**Issue by digininja** [securityroots/dradispro-tracker#199]
When moving back from a second level bullet point to a first level you've introduced an empty bullet.

If you look in the first screenshot you'll see the extra bullet between the bottom entries but in the second it isn't there. Your preview feature shows it correctly.

![bullet_point_bug_1](https://cloud.githubusercontent.com/assets/117081/4807744/11741812-5e98-11e4-9ed9-49b910c6ada9.png)
![bullet_point_bug_2](https://cloud.githubusercontent.com/assets/117081/4807745/11a614ca-5e98-11e4-8507-df0ea873baa2.png)

**Comment by rachkor** [comment]
Closing, nested bullet points are not currently supported.
