### ISSUE TITLE
corrupt word doc when screenshot is in evidence

### ISSUE THREAD

**Issue by digininja** [securityroots/dradispro-tracker#200]
My template works fine and the Word doc created opens without any problems except when I put a screenshot into the evidence, when I do Word tells me that the document is corrupt. It then manages to fix it and shows the image correctly.

I've tried this with two different projects and both failed, I then removed the screenshot from one and it opened fine so it is definitely the screenshot causing the problems.

I've mailed you a corrupt report to look at.

**Comment by etdsoft** [comment]
Looked into this, probably a template issue, can I have a look please? The generated report doesn't really help :(

**Comment by digininja** [comment]
I can see if I can reproduce it if you  want

**Comment by etdsoft** [comment]
Just a quick look at the relevant section of the template may give us a clue, even a screenshot of the corresponding Evidence tag.

**Comment by digininja** [comment]
Ok, will see what I can do.

**Comment by etdsoft** [comment]
I think this is more of a template issue than a systemic issue (e.g. have seen screenshots in Evidence work). Will close for now, please open a support ticket with the screenie of your report template (or a full document) to continue debugging.
