### ISSUE TITLE
Issue count

### ISSUE THREAD

**Issue by digininja** [securityroots/dradispro-tracker#201]
I have a table at the start of my report showing the number of highs, mediums etc, it would be good if I could create an issue control with something like

COUNT(Risk|High)

in it to get the number of highs.

While at it, I don't have use at the moment but you could also add SUM and AVERAGE. The last may be of use to show average CVSS score if that means anything.

**Comment by etdsoft** [comment]
We've implemented the IssueCounter content control to solve this problem, and we've got docs too (props to @rachkor)!

http://securityroots.com/dradispro/support/guides/word_reports/issuecounter_control.html
