### ISSUE TITLE
two underscores in a URL italicise it

### ISSUE THREAD

**Issue by digininja** [securityroots/dradispro-tracker#202]
I have a URL which has two underscores in it like this:

http://test.com/_under/_page/

how can I get it to render correctly without having "under/" in italics?

I've tried using the form:

"http://test.com/_under/_page/":http://test.com/_under/_page/

but that didn't work.

I also read that == was supposed to disable parsing but it didn't work

== http://test.com/_under/_page/ ==

and even if it did, I would lose the hyperlink.

I could make it a code block but would rather not.

Would you be able to detect that you are in a link and ignore all formatting commands?

**Comment by rachkor** [comment]
Closing, moving to the new combined tracker. Please subscribe here for updates: https://github.com/dradis/dradis-ce/issues/181
