### ISSUE TITLE
timeout on long operations/large projects

### ISSUE THREAD

**Issue by ropdor** [securityroots/dradispro-tracker#204]
I am getting timeouts on working with large projects, both during import of scan results as well as project export/creation, as follows from unicorn:

E, [2014-12-01T15:56:06.244777 #2950] ERROR -- : worker=0 PID:3042 timeout (31s > 30s), killing
E, [2014-12-01T15:56:06.327541 #2950] ERROR -- : reaped #<Process::Status: pid 3042 SIGKILL (signal 9)> worker=0

as well as nginx:
2014/12/01 16:31:30 [error] 5449#0: *4 upstream timed out (110: Connection timed out) while reading response header from upstream

I have found that changing this to 300 seconds works well. Given the lack of diagnostic/helpful errors (i.e. you just get a "something went wrong" page) I suggest increasing it to something more than 30s, and/or documenting this somewhere, would be good.

**Comment by etdsoft** [comment]
* Tool import / export should be running in the background.
* Significant SQL improvements were introduced in v2.0 and v2.1 that should be noticeable when switching projects or moving around.
* Project deletion timeouts should be address in v2.2,
