### ISSUE TITLE
Please consider removing "Please choose a project to use" after logging

### ISSUE THREAD

**Issue by urunotao** [securityroots/dradispro-tracker#205]
Just after logging-in I get "Please choose a project to use" - I think less is more in this case and it does seem to me stating the obvious :)
![screen shot 2014-12-16 at 09 44 29](https://cloud.githubusercontent.com/assets/10206517/5451455/2ed76c74-8508-11e4-80e3-0e5d26903cde.png)

**Comment by etdsoft** [comment]
Implemented will ship in v1.12
