### ISSUE TITLE
scrolling on "all issues" page

### ISSUE THREAD

**Issue by digininja** [securityroots/dradispro-tracker#208]
When there are a lot of issues on the "All issues" page, if you want to search for a new issue you need to scroll down to the bottom of the list to get to the search boxes. Once you've done the search you then have to scroll back up to the top of the page to see the results. If you need to change the search term scroll back down then back up again.

How about changing the "import issues" bit so that you enter a term and then there is a drop down to say what you are searching, it could then be spread across the top of the page rather than under the issue list.

**Comment by rachkor** [comment]
Closing, added to our internal idea backlog to investigate adding in the future!
