### ISSUE TITLE
Create Evidence Button Disappears

### ISSUE THREAD

**Issue by inadorel** [securityroots/dradispro-tracker#211]
Intermittently the 'create evidence' button is no longer visible on the screen.  This appears to be a display issue because trying various options like windowing the browser and then resizing the window,  and/or zooming in and then out sometimes (but not always) resolves the problem.

It is related to the project rather than the browser (occurs in FF 34 and IE 11)  or the server itself, because switching to a different project corrects it, and moving to a different browser and/or restarting the Dradis server itself does not.

**Comment by etdsoft** [comment]
Are you referring to the "+" sign next to Evidence? Can you attach some screenshots / steps to reproduce?

**Comment by inadorel** [comment]
Hi

It is the scaling on the screen that is somehow going wrong.  It is not the plus sign that is missing, but the link that actually enables me to associate the finding.

The first example shows it in my normal browser window (it is IE but exactly the same in FF).  The second example shows the browser zoomed out to 25% at which point I can see the button but not read the text properly.

It is definitely associated with the project rather than a browser session because Rory opened it on a different machine and it did the same thing.  I will try playing around with some of the findings to see if I can find out what is causing it once I have finished the report for the test I am working on.

Regards

Marion

**Comment by etdsoft** [comment]
Are the images missing?

**Comment by inadorel** [comment]
![example](https://cloud.githubusercontent.com/assets/3396960/5742729/4718c6a0-9c0c-11e4-8700-76585fd17aa5.PNG)
![example2](https://cloud.githubusercontent.com/assets/3396960/5742730/472361aa-9c0c-11e4-90f1-5cec58a9b4de.PNG)

I attached the images in the email - did not realize they would not be added here.

**Comment by etdsoft** [comment]
Ok, I've seen this happen before. This is because one of the pieces of Evidence you already have in that node is "too wide" and breaks the layout.
The real fix would be to improve the layout so it doesn't brake when the content is too wide.
The interim fix is going to be to switch from the current model (all Evidence for the node is pre-loaded when you click on the tree and then when you navigate the app's JS is showing / hiding the different parts) to a one-evidence at a time approach where you just load 1 note or 1 evidence every time your click on the items, so the content from one evidence won't affect others.

**Comment by digininja** [comment]
I've had this a lot, I either break long lines up with extra spaces or I
know how many tabs it takes to get to various places on the interface.

**Comment by inadorel** [comment]
Hi

Many thanks – that was exactly the problem.  I had copied a header from Burp that had an enormous cookie in it.  I deleted that piece of evidence and everything returned to normal.

Regards

Marion

**Comment by digininja** [comment]
It's usually the viewstate that messed things up for me.

**Comment by rachkor** [comment]
Closing, resolved.
