### ISSUE TITLE
Naming convention of the file exported

### ISSUE THREAD

**Issue by florencecatherine** [securityroots/dradispro-tracker#213]
When exporting files, we would like to get a file named like 'year-month-day-client-name-version0.1.docx'.  It would be great if Dradis could generate this.

Originally reported by Ray

**Comment by stephenreda** [comment]
I agree with this issue. When using advanced DOCX for export, the files is always called "dradis-word_report.docx".

**Comment by digininja** [comment]
I actually quite like this as I can save this as the raw Dradis output in
my work directory then I know that is there as the base for the report

**Comment by etdsoft** [comment]
This isn't going to change in the near future. For now we've added a Project ID to the file name as this was causing concurrency issues for large teams (if two people were exporting at the same time).
