### ISSUE TITLE
Upload does not start when the file contains the “&” in the filename

### ISSUE THREAD

**Issue by florencecatherine** [securityroots/dradispro-tracker#216]
In the Upload Manager, selecting to a file that contains the “&” in the filename, the upload doesn’t start.  I’m using the qualys plugin to import the xml results.

As reported by Angelo

**Comment by etdsoft** [comment]
Again I believe this one should be sorted as part of v1.12.0rc3. Can you let Angelo know?

**Comment by florencecatherine** [comment]
@etd email sent to Angelo
