### ISSUE TITLE
Wiki Import Search destroys Dradis

### ISSUE THREAD

**Issue by tulpn** [securityroots/dradispro-tracker#217]
We are using the Wiki Import feature for the vulnerabilities but have been having issues with some imports. 

We use a category to keep all our issues nice and tight together in the wiki, as we also use the wiki for general information and educational purposes. 

Unfortunately, when we search for some entries it completely destroys dradis import. Meaning:
It is not possible to insert a found issue anymore, because the display of the results has removed the link and malformed the results. See the image for a better illustration:

![dradis_import_issue](https://cloud.githubusercontent.com/assets/1031452/6022129/957b9024-abb2-11e4-8a0e-e3ff533bacff.png)

Is there a way to limit the Wiki Import to only include the titles rather than the entire text, or make it only search in a specific category ?

**Comment by etdsoft** [comment]
Can you provide a sample of the Wiki source code of one of the pages that is causing the problem? It seems that wiki markup is interfering with the Textile markup...

**Comment by etdsoft** [comment]
Can you provide more details for us to investigate? Otherwise I think I'll close this one.
