### ISSUE TITLE
There was an error while generating the report: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by digininja** [securityroots/dradispro-tracker#220]
Exporting a project to a docx and got this:

```
[09:37:27] Issue#895
[09:37:27] Issue#893
[09:37:27] There was an error while generating the report: undefined method `[]' for nil:NilClass
[09:37:27] Worker process completed.

**Comment by etdsoft** [comment]
There is not a lot to go with in this case. If you repeat the process does it error on the same Issue #?

Also, if you run the export from the console (as detailed [here](http://securityroots.com/dradispro/support/guides/dradisreports_debugging.html#generating-the-report-from-the-command-line)), does it error on the same Issue?

If the answer to any of these is yes, could you provide a sanitised copy of the Issue so we can try to reproduce? (you can do this by email)

**Comment by digininja** [comment]
It was something in the word template it didn't like, I was going to keep
the broken one but then overwrote it by accident, will try to reproduce it.

**Comment by digininja** [comment]
Here you go, full stack trace, will mail you the template. When you get it,
it is the last "All issues" block that kills it, when I remove that the
template works but Word does give a warning that the document is corrupt
when opening it.

Doesn't seem to be issue related as I tried it with a couple of projects
and it dies on each of them.


dradispro@dradispro:/opt/dradispro/dradispro/releases/20140926225933$
PROJECT_ID=8 RAILS_ENV=production bundle exec thor
dradis:export:advanced_word:docx --output=/tmp/
--template=/opt/dradispro/dradispro/releases/20131126124657/templates/reports/advanced_word_export/dradis_2.docx
[DEPRECATION] review your ZapUpload to ensure it includes it makes use of
the Core::Plugins::Upload. Once done, bumpt its version number to 2.10.0 in
/opt/dradispro/dradispro/releases/20140926225933/vendor/plugins/zap_upload/lib/zap_upload/meta.rb
to avoid this warning.
[DEPRECATION] review your WxfUpload to ensure it includes it makes use of
the Core::Plugins::Upload. Once done, bumpt its version number to 2.10.0 in
/opt/dradispro/dradispro/releases/20140926225933/vendor/plugins/wxf_upload/lib/wxf_upload/meta.rb
to avoid this warning.
[DEPRECATION] review your W3afUpload to ensure it includes it makes use of
the Core::Plugins::Upload. Once done, bumpt its version number to 2.10.0 in
/opt/dradispro/dradispro/releases/20140926225933/vendor/plugins/w3af_upload/lib/w3af_upload/meta.rb
to avoid this warning.
[DEPRECATION] review your TyphonUpload to ensure it includes it makes use
of the Core::Plugins::Upload. Once done, bumpt its version number to 2.10.0
in
/opt/dradispro/dradispro/releases/20140926225933/vendor/plugins/typhon_upload/lib/typhon_upload/meta.rb
to avoid this warning.
[DEPRECATION] review your SurecheckUpload to ensure it includes it makes
use of the Core::Plugins::Upload. Once done, bumpt its version number to
2.10.0 in
/opt/dradispro/dradispro/releases/20140926225933/vendor/plugins/surecheck_upload/lib/surecheck_upload/meta.rb
to avoid this warning.
[DEPRECATION] review your RetinaUpload to ensure it includes it makes use
of the Core::Plugins::Upload. Once done, bumpt its version number to 2.10.0
in
/opt/dradispro/dradispro/releases/20140926225933/vendor/plugins/retina_upload/lib/retina_upload/meta.rb
to avoid this warning.
[DEPRECATION] review your NiktoUpload to ensure it includes it makes use of
the Core::Plugins::Upload. Once done, bumpt its version number to 2.10.0 in
/opt/dradispro/dradispro/releases/20140926225933/vendor/plugins/nikto_upload/lib/nikto_upload/meta.rb
to avoid this warning.
Project found. Scoping all models to Project 8.
Loading .docx template...
Done
Found 1 issues affecting 0 nodes
Found 0 notes affecting 0 new nodes
Duplicating Node sections.
Populating Issue placeholders.
/opt/dradispro/dradispro/releases/20140926225933/vendor/plugins/advanced_word_export/lib/advanced_word_export/processors/ooxml/fields.rb:118:in
`block in populate_fields': undefined method `[]' for nil:NilClass
(NoMethodError)
        from
/opt/dradispro/dradispro/shared/bundle/ruby/2.0.0/gems/nokogiri-1.5.5/lib/nokogiri/xml/node_set.rb:239:in
`block in each'
        from
/opt/dradispro/dradispro/shared/bundle/ruby/2.0.0/gems/nokogiri-1.5.5/lib/nokogiri/xml/node_set.rb:238:in
`upto'
        from
/opt/dradispro/dradispro/shared/bundle/ruby/2.0.0/gems/nokogiri-1.5.5/lib/nokogiri/xml/node_set.rb:238:in
`each'
        from
/opt/dradispro/dradispro/releases/20140926225933/vendor/plugins/advanced_word_export/lib/advanced_word_export/processors/ooxml/fields.rb:103:in
`populate_fields'
        from
/opt/dradispro/dradispro/releases/20140926225933/vendor/plugins/advanced_word_export/lib/advanced_word_export/processors/ooxml/processor.rb:296:in
`block in process_docx_archive'
        from
/opt/dradispro/dradispro/shared/bundle/ruby/2.0.0/gems/rubyzip-1.1.6/lib/zip/output_stream.rb:60:in
`write_buffer'
        from
/opt/dradispro/dradispro/releases/20140926225933/vendor/plugins/advanced_word_export/lib/advanced_word_export/processors/ooxml/processor.rb:264:in
`process_docx_archive'
        from
/opt/dradispro/dradispro/releases/20140926225933/vendor/plugins/advanced_word_export/lib/advanced_word_export/processors/ooxml/processor.rb:54:in
`generate'
        from
/opt/dradispro/dradispro/releases/20140926225933/vendor/plugins/advanced_word_export/lib/tasks/thorfile.rb:111:in
`docx'
        from
/opt/dradispro/dradispro/shared/bundle/ruby/2.0.0/gems/thor-0.14.6/lib/thor/task.rb:22:in
`run'
        from
/opt/dradispro/dradispro/shared/bundle/ruby/2.0.0/gems/thor-0.14.6/lib/thor/invocation.rb:118:in
`invoke_task'
        from
/opt/dradispro/dradispro/shared/bundle/ruby/2.0.0/gems/thor-0.14.6/lib/thor.rb:263:in
`dispatch'
        from
/opt/dradispro/dradispro/shared/bundle/ruby/2.0.0/gems/thor-0.14.6/lib/thor/base.rb:389:in
`start'
        from
/opt/dradispro/dradispro/shared/bundle/ruby/2.0.0/gems/thor-0.14.6/lib/thor/runner.rb:34:in
`method_missing'
        from
/opt/dradispro/dradispro/shared/bundle/ruby/2.0.0/gems/thor-0.14.6/lib/thor/task.rb:22:in
`run'
        from
/opt/dradispro/dradispro/shared/bundle/ruby/2.0.0/gems/thor-0.14.6/lib/thor/task.rb:108:in
`run'
        from
/opt/dradispro/dradispro/shared/bundle/ruby/2.0.0/gems/thor-0.14.6/lib/thor/invocation.rb:118:in
`invoke_task'
        from
/opt/dradispro/dradispro/shared/bundle/ruby/2.0.0/gems/thor-0.14.6/lib/thor.rb:263:in
`dispatch'
        from
/opt/dradispro/dradispro/shared/bundle/ruby/2.0.0/gems/thor-0.14.6/lib/thor/base.rb:389:in
`start'
        from
/opt/dradispro/dradispro/shared/bundle/ruby/2.0.0/gems/thor-0.14.6/bin/thor:6:in
`<top (required)>'
        from
/opt/dradispro/dradispro/shared/bundle/ruby/2.0.0/bin/thor:23:in `load'
        from
/opt/dradispro/dradispro/shared/bundle/ruby/2.0.0/bin/thor:23:in `<main>'
zlib(finalizer): the stream was freed prematurely.

**Comment by etdsoft** [comment]
Here you go, full stack trace, will mail you the template. When you get it,
it is the last "All issues" block that kills it, when I remove that the
template works but Word does give a warning that the document is corrupt
when opening it.

Doesn't seem to be issue related as I tried it with a couple of projects
and it dies on each of them.

```
Project found. Scoping all models to Project 8.
Loading .docx template...
Done
Found 1 issues affecting 0 nodes
Found 0 notes affecting 0 new nodes
Duplicating Node sections.
Populating Issue placeholders.
//releases/20140926225933/vendor/plugins/advanced_word_export/lib/advanced_word_export/processors/ooxml/fields.rb:118:in
`block in populate_fields': undefined method `[]' for nil:NilClass
(NoMethodError)
        from
//shared/bundle/ruby/2.0.0/gems/nokogiri-1.5.5/lib/nokogiri/xml/node_set.rb:239:in
`block in each'
        from
//shared/bundle/ruby/2.0.0/gems/nokogiri-1.5.5/lib/nokogiri/xml/node_set.rb:238:in
`upto'
        from
//shared/bundle/ruby/2.0.0/gems/nokogiri-1.5.5/lib/nokogiri/xml/node_set.rb:238:in
`each'
        from
./fields.rb:103:in
`populate_fields'
        from
./processor.rb:296:in
```

**Comment by etdsoft** [comment]
Looks like the Tag definition of one of the content controls in the template was causing the problem.
