### ISSUE TITLE
Exported projects don't keep the issue tags

### ISSUE THREAD

**Issue by digininja** [securityroots/dradispro-tracker#222]
Just exported a project and imported it back into a different VM and found all the issue tags have been reset.

**Comment by etdsoft** [comment]
@digininja this should be already fixed in 1.11.2.rc5. Can you confirm?

**Comment by digininja** [comment]
Just bringing repaired laptop back up to date so haven't installed that yet, will download and install it. Will trust you that its fixed as I've no more projects to bring across.
