### ISSUE TITLE
Feature - Custom tags in VulnDB

### ISSUE THREAD

**Issue by Miketmclaughlin** [securityroots/dradispro-tracker#228]
Not really Dradis related, but is it possible to add the ability to tag vulns in vulndb, which would be searchable within the add issue search functionality?

The reasoning is we have a number of similar vulnerability wordings, but some apply to internal tests, some external, wireless etc and it would be nice to be able to differentiate these during import.

**Comment by etdsoft** [comment]
Related to #236 and yes, this was implemented in v2.1.
