### ISSUE TITLE
ssl readme is wrong

### ISSUE THREAD

**Issue by digininja** [securityroots/dradispro-tracker#230]
There is a readme file in /opt/dradispro/dradispro/current/config/ssl that talks about that directory being the location of the ssl keys but it lies, the real location is /etc/ssl/dradispro.local

**Comment by etdsoft** [comment]
Sorry about that, but you're correct, the files loaded by the server are:

```
  ssl_certificate /etc/ssl/dradispro.local/bundle.dradispro.local.crt;
  ssl_certificate_key /etc/ssl/dradispro.local/dradispro.local.key;
```

**Comment by digininja** [comment]
I did a brute force to find them, searched all text files for the phrase
ssl_certificate_key then checked out where it pointed.

**Comment by etdsoft** [comment]
Cool, the relevant file is `./config/nginx.conf`

**Comment by rachkor** [comment]
Closing. Follow the instructions here: https://dradisframework.com/pro/support/guides/customization/ssl_certificates.html
