### ISSUE TITLE
Report Template Name

### ISSUE THREAD

**Issue by florencecatherine** [securityroots/dradispro-tracker#232]
I had a report template file with spaces and &-character in the name, and Dradis froze when trying to create the report. I'm not sure if it was the spaces or the &, but you can hopefully catch this in the future.

Originally reported by Jarmo

**Comment by etdsoft** [comment]
This should be fixed in 1.12.0.rc3

**Comment by etdsoft** [comment]
@florencecatherine can you please let Jarmo know?

**Comment by florencecatherine** [comment]
@etd email sent: https://secure.helpscout.net/conversation/103212981/2303/
