### ISSUE TITLE
Feature Request: Finding replace or migrate

### ISSUE THREAD

**Issue by jnqpblc** [securityroots/dradispro-tracker#234]
I would like to see a feature that would allow me to move all evidence instances from one finding to a new one. E.g. Import Nessus, Take NessusExampleFinding1, move all finding evidence to, CustomExampleFinding1, which was pulled from MediaWiki.

**Comment by etdsoft** [comment]
This is now possible using the Rules Engine add-on and v1.12.0.rc3. The Rules Engine is compatible with IssueLibrary for importing issues, MediaWiki support will ship as part of v1.12, however depending on your network setup, if you create this sort of rule that triggers a MediaWiki API for every finding in a Nessus file, you can end up with 100s of API calls if the Nessus is big enough!

**Comment by digininja** [comment]
I assume there is going to be a nice detailed blog post on how to do this :)

**Comment by etdsoft** [comment]
Yes there will be some info in the v1.12 announcement blog, in the Support site and in the Administration guide.

**Comment by rachkor** [comment]
Closing. If the use case is not covered by the Rules Engine, Merge Issues should be used.
