### ISSUE TITLE
Feature Request: Edit evidence from issue screen

### ISSUE THREAD

**Issue by jnqpblc** [securityroots/dradispro-tracker#235]
I would like to see a feature that would allow me to edit the evidence of an asset from the issue screen.
E.g. From the "All Issue" screen, select ExampleFinding1, scroll down to see the "Assets affected by this issue", identify an asset with evidence output that needs to be modified, and select "Modify" (if there was such a thing.). This feature could either jump you to the actual evidence note within the host node or simply allow editing from there.

**Comment by etdsoft** [comment]
Implemented in v2.1
