### ISSUE TITLE
Feature Request: Set Issue Tag Color via MediaWiki

### ISSUE THREAD

**Issue by jnqpblc** [securityroots/dradispro-tracker#236]
When pulling issues from MediaWiki I would like to see the tag color also imported.

**Comment by digininja** [comment]
Wouldn't you rather pull the tag name and have that set the colour?

Or, better for me, derive the tag from an existing field such as severity.

**Comment by jnqpblc** [comment]
Yes, that is exactly what I was asking.
Either would be perfect. I just don't want to have to manually set the color via the All issues screen every time.  

--
johnqpublic

**Comment by etdsoft** [comment]
This is now possible by adding a `#[Tags]#` field to your wiki pages. More info:

http://securityroots.com/dradispro/support/guides/issuelibrary/tag_entry.html

(it also should work in MediaWiki)
