### ISSUE TITLE
Please add sorting to the "summary of issues" view

### ISSUE THREAD

**Issue by urunotao** [securityroots/dradispro-tracker#237]
Please add sorting to the "summary of issues" view, in particular by tags and by number of affected hosts

**Comment by digininja** [comment]
Already requested this, I wanted tags to have an order field so rather than
alphabetic you could order by severity so medium comes between high and low.

Came make Daniel's life too easy :)

**Comment by urunotao** [comment]
Agree, that's even better :)

**Comment by rachkor** [comment]
Closing, added to our internal idea backlog to investigate adding in the future!
