### ISSUE TITLE
Attachment "copy-01" bug

### ISSUE THREAD

**Issue by etdsoft** [securityroots/dradispro-tracker#239]
We've got some anti-clashing code that tries to detect whether a given attachment name is already taken and adds a suffix if it is. However this is not working properly and the suffix is being added even when no clashing occurs.

Reproduction steps:

> tbc

Reported by David

**Comment by dparker18** [comment]
Today this is 100% reproducible for me using Chrome on OSX. I will try to find an exception and pattern for when it does not append "copy-01"
