### ISSUE TITLE
Allow filtering on internal field controls

### ISSUE THREAD

**Issue by florencecatherine** [securityroots/dradispro-tracker#243]
Our issue note includes CVSS vector names and values:
AccessVector Local / Adjacent Network / Network
AccessComplexity High / Medium / Low
Authentication Multiple / Single / None
ConfImpact None / Partial / Complete
IntegImpact None / Partial / Complete
AvailImpact None / Partial / Complete

In the findings table in our Word template, we currently have all
combinations of these with colours and descriptions, and we manually
delete the rows which don't apply to a particular finding after the
document has been processed by Dradis.

We would like to be able to filter on these values, eg:
AccessVector Network would show as red with a description saying that
the service is accessible over the internet.
AccessVector Adjacent Network would show as orange with a description
saying that the service is accessible from within the company network.
AccessVector Local would show as yellow with a description saying that
the service is accessible to only users with a shell account.
In each case we would like the 2 inapplicable rows to be not shown.

Issue originally requested by David

**Comment by rachkor** [comment]
Closing. This can be accomplished by combining filters. E.g. `CVSS|(9.0..10.0) & AccessVector|Local & AccessComplexity|High`
