### ISSUE TITLE
bullet list formatting issue

### ISSUE THREAD

**Issue by etdsoft** [securityroots/dradispro-tracker#245]
>  -When there is a link or bolded text inside a listing, the space before is truncated. Without the listing these work as expected. This probably goes for other formattings besides just bold and link

Originally reported by Jarmo

```
* crammed https://test.com?test hyperlink

* crammed *bold* stuff
```

**Comment by rachkor** [comment]
Duplicate of https://github.com/securityroots/dradispro-tracker/issues/244 Closing as it was resolved in v2.0
