### ISSUE TITLE
Feature Request: Loosen uniqueness constraint on Project Names

### ISSUE THREAD

**Issue by dparker18** [securityroots/dradispro-tracker#247]
We would like to have multiple projects named "Penetration Test" or "PCI Compliance Audit" etc instead of duplicating the Client's name in the project name. That is currently impossible because project names need to be globally unique.

From Daniel's email reply:
Think this should be a superficial enough change. We can move the constraint to be unique within a particular Client. Can you please add this as a feature request to the tracker so it doesn't fall through the cracks?

**Comment by rachkor** [comment]
Closing, added to our internal idea backlog to investigate adding in the future!
