### ISSUE TITLE
indentation lost

### ISSUE THREAD

**Issue by digininja** [securityroots/dradispro-tracker#249]
create a node
create a subnode on it
go to all issues and add an issue
go back to all issues list and select the issue

The subnode now appears at the top level rather than indented and can be selected at that level, it is also possible to expand the top level node to get a second copy of the sub node indented under it.
![node_subnode](https://cloud.githubusercontent.com/assets/117081/7317982/0607ef1c-ea7f-11e4-9c9b-3b5252096e85.png)
![viewing_issue](https://cloud.githubusercontent.com/assets/117081/7317983/060e01a4-ea7f-11e4-80f8-c3ea1032d016.png)
![viewing_issue_expanded](https://cloud.githubusercontent.com/assets/117081/7317984/06149e74-ea7f-11e4-80e9-12ddc2f2d57e.png)

**Comment by etdsoft** [comment]
Interesting, and can reproduce.

This seems to have to do with the "Auto-update JS" that propagates changes across the project made by other users.

The good news is that only one node is created in the database.

The bad news is ... well what you've described above.

The workaround: change project to a different project and then back to this project, that seems to appease the auto-update.

The long term fix is in the making. We're working on a new version of the auto-update code for v1.12 and will watch out for this.

**Comment by digininja** [comment]
Glad you can reproduce this one. Doesn't really worry me, its rare I have
subnodes so will just ignore it till it gets fixed.

**Comment by rachkor** [comment]
Closing, resolved
