### ISSUE TITLE
updates to project selection page

### ISSUE THREAD

**Issue by digininja** [securityroots/dradispro-tracker#250]
In the nice new project selection page can you add a date for either last accessed or last updated, not sure which would be most use but either would be good.

Also the ability to sort by name and to filter by client would be good.

**Comment by etdsoft** [comment]
Filter by client is shipping in the next release. Leaving this open pending on other items.

**Comment by etdsoft** [comment]
This is implemented and the quick-filter box on the sidebar can be used to filter by client
