### ISSUE TITLE
editing nothing gives {}

### ISSUE THREAD

**Issue by digininja** [securityroots/dradispro-tracker#253]
Create a node
Select the node
Main pane gets a "Properties - edit" option
Click edit
Get
{
}

It expects some JSON, if you put some in it does get rendered, put rubbish in and get a JSON error.

**Comment by digininja** [comment]
still there in 1.12.0

**Comment by etdsoft** [comment]
This is the expected behaviour. You can store arbitrary node properties associated with a Node. These can be exported into the report too.

From v1.12 onwards the different plugins use the node's properties to store information such as host names, list of open/closed ports, etc.
