### ISSUE TITLE
refresh issue list when adding evidence

### ISSUE THREAD

**Issue by digininja** [securityroots/dradispro-tracker#257]
There are two of us working on a project, one guy writing the issues and me adding the evidence, as the issue drop down doesn't refresh when adding a new issue I have to manually refresh the page before adding evidence to get access to the new issues.

**Comment by etdsoft** [comment]
I believe this is no longer the case in 1.12.0.rc3, can you please confirm / close?

**Comment by digininja** [comment]
the drop down now updates correctly.
