### ISSUE TITLE
Hyperlinks in methodologies

### ISSUE THREAD

**Issue by florencecatherine** [securityroots/dradispro-tracker#258]
It would be really handy for us would if methodologies could contain hyperlinks. That would allow us to link to our internal wiki within the task itself.

Issue originally requested by Zach

**Comment by naranek** [comment]
How about just adding a link attribute to the task-element, and create a hyperlink when it's present. Should be pretty simple and would help us a lot.

<task link="http://www.example.com/id=123">Check this out</task>

**Comment by etdsoft** [comment]
Implemented and shipping in v2.6
