### ISSUE TITLE
The characters <, =, > causes issues to not be exported.

### ISSUE THREAD

**Issue by jklinzk** [securityroots/dradispro-tracker#259]
If the characters <, =, > are in the title filed of a dradis issue it causes the report to export with no issues.

**Comment by etdsoft** [comment]
Thanks, can you please send steps to reproduce? I've tried with this:

```
#[Title]#
Broken Title <, =, >

#[Description]#

Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
```

And this template:

![issue_259-01](https://cloud.githubusercontent.com/assets/53006/8230335/9260330a-15bf-11e5-9cab-b9d66e757e2f.png)

And got this result:

![issue_259-02](https://cloud.githubusercontent.com/assets/53006/8230340/9900abfe-15bf-11e5-9fd4-bdfb04c61ec7.png)

**Comment by jklinzk** [comment]
Sure the exact issue title was:
SSL/TLS Diffie-Hellman Modulus <= 1024 Bits (LogJam)
When I would export to our template all the issues were missing.  But when I removed <= it exported just fine.

**Comment by etdsoft** [comment]
Sorry, something else must be at play in your template, I seem to be able to use that Title without issues:

```
#[Title]#
SSL/TLS Diffie-Hellman Modulus <= 1024 Bits (LogJam)

#[Description]#

Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
```


![issue_259-03](https://cloud.githubusercontent.com/assets/53006/8253039/da7df682-168b-11e5-9b3c-db43edb1e8bf.png)

I'll leave this open for now pending other instructions to reproduce the bug.

Maybe there is some other place in the template or some other interaction that the simple template I'm use doesn't reproduce.

**Comment by etdsoft** [comment]
Closing for now, feel free to re-open if you can send us steps to reproduce.
