### ISSUE TITLE
evidence not copied to report

### ISSUE THREAD

**Issue by digininja** [securityroots/dradispro-tracker#261]
I've got a couple of issues with 396 lines of evidence, the report hasn't brought the evidence across when generated.

All the other issues/evidence has come across so it isn't a report issue as far as I can tell.

**Comment by digininja** [comment]
Just got further down and found longer ones that have come through.

There was nothing special about these two lists, just a single IP in each line, no odd line breaks or anything else.

**Comment by etdsoft** [comment]
Do we have any details on this?

**Comment by digininja** [comment]
Think it might be related to the issue with the broken template, close it and I'll reopen or create a new one if it happens again.
