### ISSUE TITLE
Add assets to issue - error when clicking to choose node

### ISSUE THREAD

**Issue by rachkor** [securityroots/dradispro-tracker#266]
In the issue view, there is a topic: Assets affected by this issue followed with link: Add. 
Clicking the link will open a search box which lists the nodes on the project. However clicking on the node in the list just causes an error dialog: "You need to choose a node that already exists in the project." I need to write the full name of the issue manually to actually add a evidence to it.

Issue originally reported by Jarmo

(Note: navigating through the list with up/down arrows and hitting enter to select does not trigger the error message, only mouse clicks)

**Comment by etdsoft** [comment]
@rachkor was this addressed by the Evidence multi-add feature of v2.4?
