### ISSUE TITLE
Node Content Control Export Error

### ISSUE THREAD

**Issue by rachkor** [securityroots/dradispro-tracker#268]
When node content control is applied, if the node names have letters åöäÅÄÖ, the word export will fail similarly to when it fails if node names have space between words.

Issue originally reported by Jarmo.

**Comment by kulisu** [comment]
got a error exporting while there are Chinese characters in node name.

CORRECT reoporting

![image](https://cloud.githubusercontent.com/assets/6811078/18418459/779b6512-7879-11e6-91c1-08c7536153b2.png)

![image](https://cloud.githubusercontent.com/assets/6811078/18418494/13f50ac6-787a-11e6-8508-b22b981abfe3.png)

WRONG reporting

![image](https://cloud.githubusercontent.com/assets/6811078/18418460/81ef44f2-7879-11e6-9a75-f472985832e5.png)

![image](https://cloud.githubusercontent.com/assets/6811078/18418492/0e5ce4d0-787a-11e6-920f-d7222641b3a4.png)
