### ISSUE TITLE
dark screen flicker

### ISSUE THREAD

**Issue by digininja** [securityroots/dradispro-tracker#269]
In the latest Chrome on Windows, selecting an entry in the evidence list then changing to another causes the browser to flicker to the dark border colour before redrawing. This doesn't happen in firefox.

It is quite off putting when quickly stepping through evidence.

Don't know if this is just my browser or on others.

rc 1.12.0.rc2

**Comment by rachkor** [comment]
Closing, new layout in v2.X should resolve this.
