### ISSUE TITLE
tagging issues leaves the "Loading..." spinning

### ISSUE THREAD

**Issue by digininja** [securityroots/dradispro-tracker#271]
Tagging an issue updates it on the backend but the UI gets stuck with the spinning wheel and the "Loading..." comment. This is in both Chrome and Firefox.

Looking at the JSON, this is what comes back, can you have an empty value for the success name?

```
{
  "success": ,
  "tag_cell": "<td style=\"color:#6baed6\"><i class=\"fa fa-tag\"><\/i> Low<\/td>"
}
```

1.12.0.rc2

**Comment by etdsoft** [comment]
fixed in rc3 ;)
