### ISSUE TITLE
Merging projects

### ISSUE THREAD

**Issue by digininja** [securityroots/dradispro-tracker#274]
Two of us with our own Pro installs are working on a test, I got the job of writing the report. It would be nice to take his project and merge it with mine so I've got a single data set to work off.

**Comment by etdsoft** [comment]
Can this be solved with the Project export plugin? You can export as Zip in the source instance, and upload it to your existing project...

**Comment by digininja** [comment]
Didn't think about that, will try it.

**Comment by etdsoft** [comment]
close?

**Comment by digininja** [comment]
ye, close it
