### ISSUE TITLE
methodology - more info

### ISSUE THREAD

**Issue by digininja** [securityroots/dradispro-tracker#280]
I'm writing my first methodology and it would be good to tag more info on to each task, something like:

task - check SSL
notes - run TLSSLed and get ssllabs screenshot

**Comment by naranek** [comment]
This gets my vote as well. We'd get a lot out of the methologies if we could put more info on them. A small comment box would also be useful for each entry, so you could include more data than just checked/unchecked.

**Comment by digininja** [comment]
comments and the commands to run would be especially good for training new
people up and reminding myself how to run the obscure commands that don't
get ran every day.

**Comment by etdsoft** [comment]
This is now implemented and shipping in v2.6
