### ISSUE TITLE
localized docx template wont work correctly

### ISSUE THREAD

**Issue by kulisu** [securityroots/dradispro-tracker#281]
Hi,

`advanced_word_export` plugin should parse the string `Placeholder Text` from _styles.xml_ instead of _document.xml_.

because localized Office likes Traditional Chinese (zh-TW) wont pop `<w:rStyle w:val="PlaceholderText"/>` when you are saving the template.

it's using style id such a3, a9 ,aff3 and references it from styles.xml, and this will cause exporting process output nothing.

you can reinstall Office by English setup disk or install language pack to solve this problem, but I think it's better to handle this on Dradis side :smile:

oh, and I've wrote a simple python script to fit current version, cheers !

**rStyle.py** 

``` python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Chris Lin @ 20150802
# sudo pip install python-docx

from docx import Document

document = Document('/Users/Chris/Downloads/Template.docx')
styles = document.styles

tagName = 'Placeholder Text'
styleId = ''

if tagName in styles:
    styleID = styles[tagName].style_id

    for attr in document.element.xpath('//w:rPr/w:rStyle'):
        if attr.val == styleID:
            attr.val = 'PlaceholderText'

    document.save('/Users/Chris/Downloads/Template-FIXED.docx')
```

**document.xml**

``` xml
<w:sdtContent>
  <w:p w:rsidRDefault="00061BC9" w:rsidRPr="00C22A81" w:rsidR="00521C52" w:rsidP="00061BC9">
    <w:pPr>
      <w:pStyle w:val="ae"/>
      <w:rPr>
        <w:rFonts w:cs="Times New Roman" w:hAnsi="Times New Roman" w:eastAsia="標楷體" w:ascii="Times New Roman"/>
        <w:sz w:val="24"/>
        <w:szCs w:val="24"/>
      </w:rPr>
    </w:pPr>
    <w:r w:rsidRPr="00C22A81">
      <w:rPr>
        <w:rStyle w:val="a9"/>
        <w:rFonts w:cs="Times New Roman" w:hAnsi="Times New Roman" w:eastAsia="標楷體" w:ascii="Times New Roman"/>
        <w:sz w:val="24"/>
        <w:szCs w:val="24"/>
      </w:rPr>
      <w:t>按一下這裡以輸入文字。</w:t>
    </w:r>
  </w:p>
</w:sdtContent>
```

**styles.xml**

``` xml
<w:style w:styleId="a9" w:type="character">
  <w:name w:val="Placeholder Text"/>
  <w:basedOn w:val="a0"/>
  <w:uiPriority w:val="99"/>
  <w:semiHidden/>
  <w:rsid w:val="00521C52"/>
  <w:rPr>
    <w:color w:val="808080"/>
  </w:rPr>
</w:style>
```

many thanks,
Chris Lin

**Comment by etdsoft** [comment]
Thanks Chris,

But it is not as clear-cut, there is no easy way (as far as I understand) to locate the placeholder style in `styles.xml`. Different localizations of Word use different `w:styleId` values.

Can you confirm using 3 or 4 documents that you always get `a9`? Or if you can create the 4 documents (1 content control in each) and send them via email I'll look into it.

**Comment by kulisu** [comment]
Hello @etdsoft,

well, cant we locate `<w:name w:val="Placeholder Text"/>` in _styles.xml_ first and find its correspond style id from parent `<w:style w:styleId="a9" w:type="character">` ?

localized templates can download: [here](https://www.dropbox.com/s/ndvufzphdjk762e/rStyle.zip?dl=0)

I'm not always got `a9` and you can find there is a style id named `a3` in the attachment above.
in a big project template (about 34 pages) is `aff6`, pretty weird, right ?
the id seems be chosen by Word randomly, so it's not a good idea to hard-coding `a?` value in the list.

**fields.rb**
```ruby
placeholder_text_list = [
  "w:sdtContent//w:rStyle[@w:val='PlaceholderText']",
  "w:sdtContent//w:rStyle[@w:val='Platzhaltertext']",
  "w:sdtContent//w:rStyle[@w:val='Tekstvantijdelijkeaanduiding']",
  "w:sdtContent//w:rStyle[@w:val='Textodelmarcadordeposicin']",
  "w:sdtContent//w:rStyle[@w:val='Besediloograde']"
]

r_style = nil
placeholder_text_list.each do |translated_xpath|
  if (sdt_field.xpath(translated_xpath).any?)
    r_style = sdt_field.xpath(translated_xpath)[0]
      break
              end
            end
```

**Comment by etdsoft** [comment]
You're right, I've found the same `<w:name w:val="Placeholder Text"/>` at least in:

* Italian localization
* Dutch localization
* Slovenian localization

It seems like we have a winner. I will look into making the change to see if there are any side-effects. I'll keep you in the loop.

**Comment by kulisu** [comment]
AWESOME !
it's worth expecting new parsing algorithm in the next version.

thanks again :beers:
