### ISSUE TITLE
prevent new registrations

### ISSUE THREAD

**Issue by digininja** [securityroots/dradispro-tracker#282]
Can I have a way to remove the ability for users to sign up from the login page. It gives anyone who can access the login page the ability to get in and see at least my client list.

**Comment by etdsoft** [comment]
Yes, it's implemented in the Settings page, and even documented w00t!

http://securityroots.com/dradispro/support/guides/administration/sign_ups.html

**Comment by digininja** [comment]
I've changed that.

A checkbox or radio button would be much more user friendly than 0 or 1.
