### ISSUE TITLE
seeing nodes from other projects

### ISSUE THREAD

**Issue by digininja** [securityroots/dradispro-tracker#285]
Two of us are working on different projects, Wes added a new node while I was sat on a node view page:

https://dradispro.local/pro/nodes/334

the node he added appeared in my nodes tree on left. As soon as I refreshed in any way it went away.

We tried it the other way and one I added appeared in his list.

**Comment by etdsoft** [comment]
Although a strange behaviour that we can't reproduce we're redoing this part for v2.0 so hopefully it won't happen again.

**Comment by etdsoft** [comment]
can I get a confirmation on whether this has happened again since v2.0 please?

**Comment by digininja** [comment]
I've not worked on it with anyone else since the upgrade so can't comment.

**Comment by etdsoft** [comment]
I'm going to close it then, feel free to re-open in the future.

**Comment by digininja** [comment]
Sure
