### ISSUE TITLE
Random Nodes show up

### ISSUE THREAD

**Issue by camelinc** [securityroots/dradispro-tracker#286]
Random Nodes, probably from other projects get listed in the left tree-navigation. Always seem to be the same nodes that are listed.

To reproduce:
1) "All Issues"
2) open details of any issue
3) other non project related nodes are listed

**Comment by digininja** [comment]
This is probably a duplicate of my #285 or at least related.

**Comment by etdsoft** [comment]
Using #285 as canonical description for this problem.
