### ISSUE TITLE
bad parsing URL in Textile

### ISSUE THREAD

**Issue by kulisu** [securityroots/dradispro-tracker#290]
**Dradis**
# [_Parameters]

text.www.example.com
# [_Payload]

bc.. GET / HTTP/1.1
Host: sub.www.example.com

**Response**

``` html
<h4>_Parameters</h4>
<p>text.<a href="http://www.example.com">www.example.com</a></p>

<h4>_Payload</h4>
<pre>
  <code>
    GET / HTTP/1.1
    Host: sub.<a href="http://www.example.com">www.example.com</a>
  </code>
</pre>
```

**Browser**

![image](https://cloud.githubusercontent.com/assets/6811078/9325551/c1047776-45c5-11e5-8c66-0a286ef66b5b.png)

**Report**

![image](https://cloud.githubusercontent.com/assets/6811078/9325642/7357afb0-45c6-11e5-8348-7b7ea4a040ed.png)

**Comment by rachkor** [comment]
Closing, duplicate of https://github.com/securityroots/dradispro-tracker/issues/321
