### ISSUE TITLE
Rules Engine Error: Nessus + "contains"

### ISSUE THREAD

**Issue by rachkor** [securityroots/dradispro-tracker#291]
Rules like the following:
![nessus-upload-2](https://cloud.githubusercontent.com/assets/11186655/9420461/28b8cf20-4823-11e5-96ff-13c0ddb2800f.PNG)

Produce an error when importing the nessus file: 
![nessus-upload](https://cloud.githubusercontent.com/assets/11186655/9420371/0a755534-4822-11e5-87be-ff908db9bea8.PNG)

Issue originally reported by Michael

**Comment by etdsoft** [comment]
the field should be `plugin_name`. Can you confirm as a workaround that if yo use `plugin_name` instead of `report_item.plugin_name` this goes away?

**Comment by rachkor** [comment]
@etdsoft updated screenshot to be plugin_name instead of report_item.plugin_name but I am getting the same error. It also errors the same with other fields (not just plugin_name) as long as the "contains" trigger is selected.
