### ISSUE TITLE
client filter on "project selection" page

### ISSUE THREAD

**Issue by digininja** [securityroots/dradispro-tracker#293]
It would be good to have a client filter on the projects page rather than having to go through the client list page.

**Comment by etdsoft** [comment]
As a workaround, can you use the filter box in the sidebar and enter the client name you're looking for?

**Comment by digininja** [comment]
That does work and will help but it has just shown up a UI problem....

I've got 5 projects in the recent list which makes it cover 2 lines, I
started typing in the box and nothing appeared to happen, it was only when
I noticed the scrollbar changing length that I realised that it was
changing the list at the bottom and I had to scroll down to see the filter.

**Comment by etdsoft** [comment]
Yup, we're working on it ;)

**Comment by digininja** [comment]
great.

**Comment by rachkor** [comment]
Closing, added to our internal idea backlog to investigate adding in the future!
