### ISSUE TITLE
IssueLibrary - 'Send Issue to Library' entries stuck as Pending

### ISSUE THREAD

**Issue by rachkor** [securityroots/dradispro-tracker#294]
I've sent an issue to the library however, when I've gone to change the issue library status to Active it says "Entry Updated" but remains to be "Pending".

Issue originally reported by Callum 

Note: Entries added manually are stuck marked as Active even when originally created as Draft, Archive, or Pending and the status doesn't change when the entry is updated.

**Comment by etdsoft** [comment]
This was fixed and shipped in v2.1
