### ISSUE TITLE
Parenthesis breaks link display in Word export

### ISSUE THREAD

**Issue by rachkor** [securityroots/dradispro-tracker#296]
Link is working correctly but Dradis is cutting the parenthesis. 

Example: 
https://www.owasp.org/index.php/Testing_for_cookies_attributes_(OTG-SESS-002)
Displays correctly within Dradis but after exporting to Word, it displays without the parenthesis at the end even though the hyperlink is still correct: 

![dradis](https://cloud.githubusercontent.com/assets/11186655/9534526/433489f4-4cd6-11e5-88dd-5c927881484a.png)

This display issue is not affected by capital letters, underscore, etc. 

Issue originally reported by Ender.

**Comment by etdsoft** [comment]
Related to #244 The trailing `(OTG-SESS-002)` is being treated as the link's `:title` instead of as part of the link's text. I've inquired upstream about this:

https://jgarber.lighthouseapp.com/projects/13054-redcloth/tickets/279-links-with-a-name-that-contains-a-trailing-whatever

**Comment by rachkor** [comment]
Closing, duplicate of dradis/dradis-ce#174. Please follow there for updates
