### ISSUE TITLE
can't import main ova into ESXi 5.5

### ISSUE THREAD

**Issue by digininja** [securityroots/dradispro-tracker#297]
Trying to import the main Dradis application downloaded from your site into ESXi 5.5 I get this error:

```
Unsupported hardware family virtualbox-2.2
```

It is a well known one that requires some messing to fix, here is one example:

http://www.itsecurenet.com/virtualbox-ova-to-vsphere-ovf/

Unfortunately if I download the ova file to my Windows box to process it it will take weeks to upload the 3.3G file to the server I need it on, any chance of fixing the image at your end and giving a true VMWare image?

**Comment by etdsoft** [comment]
We've got an XML that does the trick, is it an option to:

1. rename to .tar
2. extract
3. edit .ovf and make some changes
4. import that .ovf

All in the target server you need to deploy?

**Comment by digininja** [comment]
That would work. I've got the ova sat on a machine with nice fast
connection to the esxi server so can make the changes in there

**Comment by etdsoft** [comment]
We dealt with this on Slack and now have an OVA that works on this env.
