### ISSUE TITLE
urls come into word in larger font

### ISSUE THREAD

**Issue by digininja** [securityroots/dradispro-tracker#298]
I don't know if this is because of my template or not, but if Dradis picks up that there is a URL in text it is importing into Word then rather than the 9 point font of the rest of the document the URL is in 10 point.

**Comment by etdsoft** [comment]
Links should get Word's `Hyperlink` style. If in the generated document you create another link (e.g. new paragraph, type "http://drad.is"  - minus the "s - and Enter), does the manual link get the same style as the Dradis-generated one?

**Comment by digininja** [comment]
It picks up the colour and underline but the font size is the same as the
rest of the text.

I'll have a look for the hyperlink style and see what that is set to on the
template

**Comment by etdsoft** [comment]
Thanks. I can't reproduce this problem at the moment. I suspect this is a template issue where you standard style is set to 9 point, but somehow the Hyperlink style is set to 10.

**Comment by digininja** [comment]
Sounds like it.
