### ISSUE TITLE
Word doc export fail

### ISSUE THREAD

**Issue by digininja** [securityroots/dradispro-tracker#301]
On fresh 1.20.0 install, selecting the basic.xslt default template causes this error while exporting

```
This page refreshes automatically, sit back and relax while we churn that report for you!
[08:08:19] Enqueueing job to start in the background. Job id is 4
[08:08:21] Project: External Test
[08:08:21] Worker process starting background task.
[08:08:21] Loading .docx template...
[08:08:21] Done
[08:08:21] Found 56 issues affecting 86 nodes
[08:08:21] Found 1 notes affecting 0 new nodes
[08:08:21] Adding 0 new nodes with properties but no issues/evidence.
[08:08:22] There was an error while generating the report: Zip end of central directory signature not found
[08:08:22] Worker process completed.

**Comment by etdsoft** [comment]
> [08:08:22] There was an error while generating the report: Zip end of central directory signature not found

This seems to indicate a problem with the template file (.docx -> Zip archive). Can you confirm the template file is good (it's not zero size, it opens in Word, etc.)?

**Comment by etdsoft** [comment]
I see the problem now `basic.xslt` is an XSLT template not a .docx file.

Can you try this with the default .docx template (`default_dradis_template_v1.7.docx`) or your own template?

**Comment by digininja** [comment]
basic_fields.docx worked but trying to open in Word 2013 gives:

Ambiguous cell mapping encountered. Possible missing paragraph element. <p>
elements are required before every </tc>

Location: Part /word/document.xml, ine 33, Column 13

**Comment by etdsoft** [comment]
This is because there is a placeholder in the document (inside a table cell) for a field and at least one of the issues in the project doesn't provide a value for that field.

We're working on a "pre-export" check that would highlight this type of problem and point you in the right direction if there are any missing field values. Will ship in next release. Leaving this open for now.

**Comment by digininja** [comment]
Do you have a sample note template that would give enough information to
work with this default template?

**Comment by etdsoft** [comment]
```
#[Title]#

#[IPAddress]#

#[Hostname]#

#[OS]#
```

But I'd recommend you use these other samples and templates as they are more real-life like:

https://portal.securityroots.com/extras/configurations

**Comment by digininja** [comment]
That worked but as the project has already imported a Nessus scan I still
get the error when opening the document and in the document there is an
almost empty table with just my single new entry at the end.

I can understand why this is acting as it is but it needs something so that
there aren't huge empty tables and errors when tool imports have been done
and they don't match up with the templates.
