### ISSUE TITLE
Acunetix plugin not importing all findings

### ISSUE THREAD

**Issue by rachkor** [securityroots/dradispro-tracker#303]
It leaves out some issues, and the evidence that should belong to them is attached to another issue. So in Acunetix we have 12 issues, but in Dradis only 8 and one of them has quite a lot of unrelated evidence. 

Steps to reproduce:

1. Create a new project
2. Import acunetix results from the file

This is the view from acunetix :
![image001 1](https://cloud.githubusercontent.com/assets/11186655/10079956/26627eb4-62aa-11e5-8f7a-38f24896afe0.jpg)
Here is a list of issues in Dradis:
![image002](https://cloud.githubusercontent.com/assets/11186655/10079960/2b04ddcc-62aa-11e5-90eb-ef4320d17120.jpg)
You can see that there's a lot less issues, and HTML form without CSRF protection has 23 evidences.

Issue initially reported by Jarmo

**Comment by etdsoft** [comment]
Fixed will ship in next release. See commit in dradis/dradis-acunetix@e3d5f46 for a workaround / hot patch.
