### ISSUE TITLE
Error changing the encrypted volume’s key

### ISSUE THREAD

**Issue by rachkor** [securityroots/dradispro-tracker#304]
Following the guide at http://securityroots.com/dradispro/support/guides/disk_encryption.html#changing-the-encrypted-volume-s-key results in the following error: 

![dradiskeychange](https://cloud.githubusercontent.com/assets/11186655/10107609/7870e93c-6379-11e5-99e3-fca4bea8275a.png)

Issue initially reported by James

**Comment by etdsoft** [comment]
Good spot, the line in the docs is wrong (from an old VM). Can you please update the guide and then close this issue?

This is the right command:

```
# cryptsetup luksChangeKey /dev/disk/by-uuid/ae6501ed-38da-43ad-b6fd-199e529120e8
```

**Comment by rachkor** [comment]
Closing, follow the guide here: https://dradisframework.com/pro/support/guides/customization/auto-unlock-luks-encrypted-drive.html
