### ISSUE TITLE
old styling

### ISSUE THREAD

**Issue by digininja** [securityroots/dradispro-tracker#305]
This page still has the old styling

/pro/admin/ruleengine/rules

**Comment by etdsoft** [comment]
Thanks for the heads up. There is a little bit of JS trickery in the view that prevented us from migrating it to the new "MintCreek" theme. We'll do before 2.0 final though...

**Comment by etdsoft** [comment]
Looks like this one didn't make the cut for v2

**Comment by etdsoft** [comment]
But it did for v2.1
