### ISSUE TITLE
Project Node List Flattens Out

### ISSUE THREAD

**Issue by rachkor** [securityroots/dradispro-tracker#306]
"Occasionally on a page load the tree contents freak out and flatten into an enormous list."

Steps to Reproduce: 
1. Create a new project with the following Node Structure: 
Scope
Hosts
- 10.0.0.1
- 10.0.0.2
- 10.0.0.3

Nodes display in sidebar as: 
![nodes](https://cloud.githubusercontent.com/assets/11186655/10145836/c3dc4b30-65e2-11e5-9918-3945dcbee12a.PNG)

2. Add an issue to that project and navigate to it (/pro/issues/####)
Nodes flatten out and display in sidebar as: 
![image](https://cloud.githubusercontent.com/assets/11186655/10145816/a3e1cb8e-65e2-11e5-83f2-2c99bce12a63.png)

Issue Originally reported by David

**Comment by etdsoft** [comment]
Fixed, ships in next release / pre. Please notify David.
