### ISSUE TITLE
Node Expand Issues

### ISSUE THREAD

**Issue by rachkor** [securityroots/dradispro-tracker#307]
1. The expand button is always displayed, even if a node has no children. As soon as you click it, it disappears. We make pretty liberal use of nodes and subnodes so we have to click each one to see where there's data.

2. When you click on a node and a new page is loaded, the entire tree structure collapses and you lose your place.

Issue Initially reported by David

**Comment by etdsoft** [comment]
1. We need to look into this.

2. Fixed, will ship in next release.

**Comment by etdsoft** [comment]
We shipped a broken fix in 2.0, fixed in 2.0.5
