### ISSUE TITLE
Feature Request: Author Permissions

### ISSUE THREAD

**Issue by rachkor** [securityroots/dradispro-tracker#308]
1. We’d like to add/remove the ability of author users to view the entire list of clients. For now, users with an “author” role can view our clients list. 
2. Authors should not be able to add or remove users from projects

Feature originally requested by Erik

**Comment by dparker18** [comment]
Agreed, is a more granular permissions model on the roadmap that will cover these items and more? Happy to help define use cases

**Comment by rachkor** [comment]
Closing, adding to our internal idea backlog to investigate changing in the future.
