### ISSUE TITLE
Hyperlink Invalid Predicate error

### ISSUE THREAD

**Issue by rachkor** [securityroots/dradispro-tracker#311]
The following URLs in a report in a note led to the following error in exporting, preventing the document from processing. This may be an XML injection type of issue within Dradis.
![hyperlinks-2](https://cloud.githubusercontent.com/assets/11186655/10294696/2f77c270-6b79-11e5-8e0b-7704c891cd22.PNG)

![hyperlinks-1](https://cloud.githubusercontent.com/assets/11186655/10294695/2f772cca-6b79-11e5-8727-d56429cac16e.PNG)

Issue initially reported by Erik

**Comment by TheDauntless** [comment]
I've encountered this issue just now:

> [08:33:29] There was an error while generating the report: Invalid predicate: //r:Relationship[@Target='http://player.vimeo.com/video/'%2bid%2b'title=0&byline=0&portrait=0&wmode=transparent' and @Type='http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink']

**Comment by rachkor** [comment]
@TheDauntless, can you try wrapping the problem link in a code block?
 Here are more details on that error: https://dradisframework.com/pro/support/guides/debug_template/failed_export.html#invalid-predicate. In your case, it looks like the single quotes in the link may be causing problems.
