### ISSUE TITLE
Feature Request: Filter Evidence

### ISSUE THREAD

**Issue by rachkor** [securityroots/dradispro-tracker#313]
Currently there is no way to sort/filter the Evidence control. 

"In our template we include one example evidence in the main report, and the rest is put into an appendix. We would like to have a flag on the evidence ("example") that can be used to include it in the main body. However, we have not been able to find a way to filter on evidence."

Feature originally requested by Chad

**Comment by etdsoft** [comment]
Sanity check, was this shipped in v2.5?

**Comment by rachkor** [comment]
Confirmed! This shipped in v2.5.
