### ISSUE TITLE
Author accounts are added twice to new projects

### ISSUE THREAD

**Issue by rachkor** [securityroots/dradispro-tracker#315]
Authors get two entries when they create a new project. They're added twice to the project (duplicate avatars) and the project appears twice on the /pro/projects page. 

To replicate: 
1. Sign in as an Author
2. Create a new project. Under "the team" make sure the checkbox next to the Author account is selected. 
3. Verify on the /pro/projects page that the new project appears twice and that the Author account was added twice

Workaround: 
​1. Sign in as an Author
​2. Create a new project. Under "the team", unselect the checkbox next to your Author account. 
​3. Verify on the /pro/projects page that the new project appears once and the Author account was only added once. 

Issue originally reported by Boglarka

**Comment by etdsoft** [comment]
Fixed will ship in next release
