### ISSUE TITLE
Special characters bc error

### ISSUE THREAD

**Issue by rachkor** [securityroots/dradispro-tracker#316]
Special characters (€, ä, Ã, È, etc) do not export properly in block code format. 

In bc. or bc.., the special characters export into Word as ??. They export properly outside of the code blocks or within p.

Example in Dradis
![bc-01](https://cloud.githubusercontent.com/assets/11186655/11346903/4747734e-91dc-11e5-82a6-126dfc149fe9.png)

Example on export: 
![bc-02](https://cloud.githubusercontent.com/assets/11186655/11346905/487e25c8-91dc-11e5-9530-b7d4b76d4f6e.png)

Issue originally reported by Jarmo

**Comment by kulisu** [comment]
got a error exporting while there are Chinese characters in `bc.` and `bc..`

**Comment by kulisu** [comment]
Hi @etdsoft, this patch works like a charm thanks !

![image](https://cloud.githubusercontent.com/assets/6811078/22825220/e6f3baee-efc6-11e6-8c49-a41ba3992f27.png)

![image](https://cloud.githubusercontent.com/assets/6811078/22825204/cc8be7c6-efc6-11e6-8ecb-f5bfd9ee1dba.png)

**Comment by etdsoft** [comment]
Perfect, it's merged now and will ship into the next release
