### ISSUE TITLE
Nmap Import Doesn't Identify OS

### ISSUE THREAD

**Issue by wyoung4324** [securityroots/dradispro-tracker#317]
Importer does not properly translate OS match field.  See screenshot below.

![image](https://cloud.githubusercontent.com/assets/16085666/11476955/133f9c60-974b-11e5-9a28-f47aa6354f64.png)

**Comment by etdsoft** [comment]
Can you verify the Properties of the corresponding node? Does the OS show up there?

**Comment by etdsoft** [comment]
I've confirmed that the Properties of the node should display the right OS string

**Comment by etdsoft** [comment]
Feel free to re-open with more info
