### ISSUE TITLE
IssueFieldValidator also validates Notes

### ISSUE THREAD

**Issue by rachkor** [securityroots/dradispro-tracker#319]
The IssueFieldValidator currently validates the field names and contents for Notes and Issues instead of just Issues. 

When running validation for issue fields, the validator checks all notes and not just issues. These notes have their own fields that are associated with them that do not correspond to issue fields - e.g. "Rating". 

Bug initially reported by Ray

**Comment by digininja** [comment]
agreed, I'm seeing the same thing

**Comment by etdsoft** [comment]
Fixed, will ship in next release
