### ISSUE TITLE
Projects page shows 0 notes for populated projects

### ISSUE THREAD

**Issue by rachkor** [securityroots/dradispro-tracker#328]
The `/pro/projects` page shows `0 notes` for all but the most currently-updated project even if other projects have >0 notes. 

Example (all 3 projects have at least 10 notes):
<img width="898" alt="screen shot 2016-05-05 at 12 35 17 pm" src="https://cloud.githubusercontent.com/assets/11186655/15076807/14f4db36-1371-11e6-86e7-0f71078aac04.png">

If you click Edit and update the project, `/pro/projects` will still show `0 notes` but if you open the project and make changes to the project content (e.g. edit an Issue), `/pro/projects` will update and show the number of notes for that project (and only that project). 

Bug originally reported by Ray.

**Comment by digininja** [comment]
I'm seeing similar except the current project often has 0 as well as the others.

**Comment by rachkor** [comment]
Closing, resolved.
