### ISSUE TITLE
Code Inside Evidence Note Causes Exported Word Document XML Errors

### ISSUE THREAD

**Issue by wyoung4324** [securityroots/dradispro-tracker#329]
Had an issue where the exported word document was unable to be opened due to XML errors.  Tracked down the problem to a piece of evidence in my project.  Putting it here to aid in tracking down what types of characters cause export issues.  Evidence text is attached.
[evidence.txt](https://github.com/securityroots/dradispro-tracker/files/275098/evidence.txt)

**Comment by etdsoft** [comment]
what if you use the "block of code" marker? (`bc. ` or `bc.. `)?

**Comment by kulisu** [comment]
DO NOT use `pre.` and `pre..` markers in your notes, these also cause errors while you trying to open a exported-report.

**Comment by wyoung4324** [comment]
I actually can't get back into the project to test that out Daniel.  Getting the generic error page every time I try to load it up now.  My temporary solution was to just remove the evidence and paste it in the word document post export.  The real issue though is generally finding which note in Dradis is causing the problem with the export.  How do I know when to use the block code markings, or should we just use them on anything containing some type of code?  

Feel free to close this issue, I just thought you might be interested in the data.

**Comment by etdsoft** [comment]
Yes, in general, `bc.` and `bc..` should always be used to mark blocks of code, HTTP snippets, etc.
