### ISSUE TITLE
Feature request: Display report template title not filename in the export manager

### ISSUE THREAD

**Issue by rachkor** [securityroots/dradispro-tracker#332]
Currently, the report template filenames appear as a list in the Export Manager (e.g. `/pro/export`). 

![projects-32](https://cloud.githubusercontent.com/assets/11186655/16087325/44ece450-32e8-11e6-91f7-e5a3332b50e0.png)

Instead, can we have the Title field from the Report template details (`/pro/admin/templates/reports/123/edit`) listed in the Export Manager listed when we export a report?

<img width="1221" alt="screen shot 2016-06-15 at 11 02 23 am" src="https://cloud.githubusercontent.com/assets/11186655/16087468/aede1a78-32e8-11e6-88f6-aa8503f16b84.png">

Feature initially requested by both Michael and Arnaud

**Comment by digininja** [comment]
I'd like this as well.

**Comment by etdsoft** [comment]
Implemented, ships in the next release.

**Comment by etdsoft** [comment]
@rachkor can you ping the original requestors please?

**Comment by rachkor** [comment]
@etdsoft done, thank you!
