### ISSUE TITLE
Bug: license renewal link displays HTML tags

### ISSUE THREAD

**Issue by rachkor** [securityroots/dradispro-tracker#335]
The "License is about to expire" link to renew your license does not display correctly in the header, showing the <a> tags instead of a hyperlink: 

![image](https://cloud.githubusercontent.com/assets/11186655/16625335/9c9e88e8-4369-11e6-8350-11641f1ae685.png)

**Workaround:** 
Navigate directly to `/pro/license/renew` on your instance. 

_Bug initially reported by Joseph_

**Comment by ryuspeed** [comment]
On our instance, /pro/license/renew does not exist as a URL. The actual URL is /pro/license/new

**Comment by rachkor** [comment]
Moving to the new combined tracker. Please subscribe here for updates: https://github.com/dradis/dradis-ce/issues/185
