### ISSUE TITLE
Preview of markdown table not working in Issue Library

### ISSUE THREAD

**Issue by TheDauntless** [securityroots/dradispro-tracker#344]
Markdown tables aren't probably shown in the preview tab of the issue library. The exact same issue *is* shown correctly in the preview tab inside the project. This is on Dradis Pro 2.5.

1) Create an issue in the issue library that contains a table:
<img width="315" alt="screen shot 2017-01-31 at 09 18 13" src="https://cloud.githubusercontent.com/assets/1650034/22457103/535e68e8-e796-11e6-9e57-cf7fc8027e2f.png">
2) View table in preview. The preview is not working:
<img width="345" alt="screen shot 2017-01-31 at 09 18 03" src="https://cloud.githubusercontent.com/assets/1650034/22457114/5d2d60ae-e796-11e6-951b-af3eff9ddd34.png">
3). Save issue and import into project. The preview is correct:
<img width="660" alt="screen shot 2017-01-31 at 09 14 33" src="https://cloud.githubusercontent.com/assets/1650034/22457126/6861730c-e796-11e6-878b-47246206c3a0.png">

**Comment by etdsoft** [comment]
Hi @TheDauntless thanks for the report, can you use the browser console to confirm if there is HTML table markup in the page? I suspect this is a styling / CSS issue.

**Comment by TheDauntless** [comment]
It does indeed appear to be CSS issue:

<img width="475" alt="screen shot 2017-01-31 at 09 26 11" src="https://cloud.githubusercontent.com/assets/1650034/22457335/529ea034-e797-11e6-8974-7984fd3851bd.png">

**Comment by rachkor** [comment]
Closing, added to our internal idea backlog to investigate adding in the future!
