### ISSUE TITLE
moving a sub node gets disappeared

### ISSUE THREAD

**Issue by kulisu** [securityroots/dradispro-tracker#346]
reproduce steps:

1. add a `top node` named example.com
2. add `sub nodes` named f1 and f1_2010 to example.com
3. move f1_2010 node to f1, and **all sub nodes** in example.com get disappeared

![](http://g.recordit.co/MEMwjQiuCI.gif)

**Comment by etdsoft** [comment]
I can confirm this bug, the good news is that the nodes are still in the DB (i.e. you can access them by ID).

**Comment by etdsoft** [comment]
We've looked into it, it's a combination of a UI issue and a DB issue. The app is getting confused about what nodes have or don't have children and the UI gets messed up.

This seems to be a bug upstream that we're investigating:

https://github.com/amerine/acts_as_tree/issues/63

I'll update this thread as soon as we know more.

**Comment by rachkor** [comment]
Moving this to the new combined tracker. Please subscribe here for updates: https://github.com/dradis/dradis-ce/issues/179
