### ISSUE TITLE
pasted image cant assign file name

### ISSUE THREAD

**Issue by kulisu** [securityroots/dradispro-tracker#349]
## Reproduce Steps:

1. Copy image you want to upload by Ctrl+C / Command+C
2. Paste image to Dradis Pro page by Ctrl+V / Command+V
3. And the prompt box `Please provide a filename for the pasted image` wont popup in the latest Chrome.

## Version Info

Dradis Pro Version: 2.6.0
Chrome Version: 58.0.3029.110 (64-bit)

## Live Screenshot

![](http://g.recordit.co/07fj6qjWOD.gif)

**Comment by rachkor** [comment]
@kulisu thanks for sending the over! I was able to replicate this on my local system. The `Please provide a filename for the pasted image` popup appeared with Chrome v57.##. I updated to v58.## and the popup is no longer appearing! We'll keep digging and let you know what we can find.

**Comment by etdsoft** [comment]
@kulisu can you confirm PR156 addresses the issue please?

**Comment by kulisu** [comment]
Hi @etdsoft and @aapomm,

this works like a charm and alleviates ours pain, many thanks !
![](http://g.recordit.co/BQIBAQ1lWx.gif)

**Comment by etdsoft** [comment]
Ships in the next release.
