### ISSUE TITLE
Feature Request: An indication that an issue has already been sent to the IssueLibraryr

### ISSUE THREAD

**Issue by leesoh** [securityroots/dradispro-tracker#350]
Working through a site with lots of new vulns, I send a lot to the library. With hundreds of vulns sent, its hard to keep track of those that I've already sent. Current workflow has me checking issuelibrary as I review each vuln.

**Comment by rachkor** [comment]
Thanks @leesoh! Closing: added to the idea backlog to consider adding in the future.
