### ISSUE TITLE
Mobile UI problem

### ISSUE THREAD

**Issue by dormi** [securityroots/dradispro-tracker#352]
#ryan reported:
 
> Dradis needs a bit of UI work when it comes to mobile. For instance this I can’t select the top project cause the name is behind the menu screen. This was on a 10.5in IPad Pro.

![image uploaded from ios](https://user-images.githubusercontent.com/85766/28003133-6585c3f4-653b-11e7-8f09-daf2f00beeb3.jpg)

**Comment by rachkor** [comment]
Closing, added to our internal idea backlog to investigate adding in the future!
