### ISSUE TITLE
BI Engine search improvement: being able to search by partial words

### ISSUE THREAD

**Issue by dormi** [securityroots/dradispro-tracker#353]
as we do in the Client page.
<img width="582" alt="client_page_search" src="https://user-images.githubusercontent.com/85766/28013041-03a2671e-6568-11e7-87ad-7195fb4beae0.png">

but in the BI page, the search must be an exact match:
<img width="580" alt="bi_search_page" src="https://user-images.githubusercontent.com/85766/28013079-20eb1244-6568-11e7-8488-d52be398db57.png">

**Comment by rachkor** [comment]
Closing: added to the idea backlog to consider adding in the future.
