### ISSUE TITLE
Nested evidence in word reports don't work properly

### ISSUE THREAD

**Issue by dormi** [securityroots/dradispro-tracker#354]
When in a word report template we use a structure like this one:
`Node > Issue > Evidence`
the report is populated with all `Evidence` for that `Issue`, not only the ones that relate the `Issue` to the `Node`.

That may be understood as the `Issue` is forcing its own scope.
But if I want to just check all evidence for that `Node` and I try:
`Node > Evidence`
this seems to provide an empty list of `Evidence`.

----

Thank you @kulisu for reporting this

**Comment by rachkor** [comment]
Closing, moving this over to https://github.com/dradis/dradis-ce/issues/175. Please subscribe there for updates! (@kulisu)
