### ISSUE TITLE
[Idea] Searching in notes

### ISSUE THREAD

**Issue by bolek117** [securityroots/dradispro-tracker#48]
In everyday work is really useful to search for some words in notes content. At this moment in new interface there is no possibility to "grep" through node/notes content.

**Comment by digininja** [comment]
Is this still likely to appear in 1.13? I really need it for the job I'm on now, digging through 10's of notes trying to find where I referenced a specific user.

**Comment by etdsoft** [comment]
This shipped in v2.4
