### ISSUE TITLE
no menu after edit evidence

### ISSUE THREAD

**Issue by digininja** [securityroots/dradispro-tracker#62]
In the new interface updated this morning...

Go to a node, click to expand an evidence block, click edit
Click cancel

Get a list of evidence but no menu.

Similar if you click update then use the back to node evidence list.

**Comment by etdsoft** [comment]
Can you confirm whether this is still an issue? Don't seem to be able to reproduce.

"Get list of evidence but no menu" <- Is this the menu you'd normally get in the "+" to the right of Evidence, or something else?

**Comment by digininja** [comment]
Currently got the latest beta downloading so will try it with that in the
morning.

**Comment by digininja** [comment]
Just checked, looks like you fixed it in the year and half since I raised it :)

**Comment by etdsoft** [comment]
Users! Even when you fix their reported bugs still they are not happy!!
