### ISSUE TITLE
[new interface] Scroll content bar independently

### ISSUE THREAD

**Issue by etdsoft** [securityroots/dradispro-tracker#66]
Originally reported by @digininja:

"
I've now got a few issues in, enough to make me need to scroll to see
them. I scroll to the last one in the list and select it, the content
box is also scrolled down so I now have to scroll back up again to see
the content. If I want to change issues I have to scroll back down
again then back up for content....

Can you have the notes/issues block in its own scrolly area?
"

**Comment by rachkor** [comment]
Closing, resolved.
