### ISSUE TITLE
note editor selection doesn't get cleared down

### ISSUE THREAD

**Issue by digininja** [securityroots/dradispro-tracker#76]
In firefox, windows.

Edit an existing note
Highlight a section of it
Cancel editing
Select a different note
Edit it
The previous highlighting remains.

**Comment by etdsoft** [comment]
I believe this is no longer the case in 1.12.0.rc3. Can you please verify / close?

**Comment by digininja** [comment]
not sure as I just found a new bug, will raise it now.

**Comment by etdsoft** [comment]
Can't reproduce. Feel free to re-open if current.
