### ISSUE TITLE
Methodologies: allow a particular methodology to be added within a particular node

### ISSUE THREAD

**Issue by poser** [securityroots/dradispro-tracker#93]
In the "old nodes" view (but not the other two views), it is possible to add a link, anywhere in the node tree, to the set of methodologies that have been created. This links to the full list of methodologies, however, whereas a shortcut to one particular methodology (either by showing _only_ that methodology or by showing the full set, but pre-selecting the desired methodology) would be more useful.

And, of course, the newest view mode lacks any way to create "shortcuts."

**Comment by rachkor** [comment]
Closing, references the old version of the Methodologies feature.
